name: hw-probe
version: 1.4-1
summary: A tool to check operability of computer hardware
description: >
 A tool to check operability of computer hardware and upload result
 to the Linux hardware database.
     
 Probe — is a snapshot of your computer hardware state and system
 logs. The tool returns a permanent URL to view the probe of the
 computer.
     
 The tool is intended to simplify collecting of logs necessary for
 investigating hardware related problems. Just ask user to run one
 simple command to collect all the system logs at once:
 
     sudo hw-probe -all -upload
 
 By creating probes you contribute to the HDD/SSD Real-Life
 Reliability Test study: https://github.com/linuxhw/SMART
     
 The tool is released under the GNU LGPL 2.1+ license.
     
type: app
confinement: classic
grade: stable
apps:
  hw-probe:
    command: usr/bin/hw-probe -snap
    environment:
      PATH: $PATH:$SNAP/sbin:$SNAP/usr/sbin:$SNAP/usr/bin
      PERL5LIB: $SNAP/usr/share/perl5
      LD_LIBRARY_PATH: $SNAP/lib/x86_64-linux-gnu/:$SNAP/usr/lib:$SNAP/usr/lib:$SNAP/usr/lib64:$SNAP/usr/lib/x86_64-linux-gnu
parts:
  edid-decode:
    source: https://git.linuxtv.org/cgit.cgi/edid-decode.git
    source-type: git
    plugin: make
    override-build: |
      sed -i -e 's/ -g / /' Makefile
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - make
    prime:
      - usr/bin/edid-decode
  libkmod:
    source: http://ftp.riken.jp/Linux/kernel.org/linux/utils/kernel/kmod/kmod-12.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      ./configure --disable-debug --disable-python --disable-logging --disable-tools --disable-test-modules --disable-manpages --prefix=/usr
      sed -i -e 's/ -g / /' Makefile
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - make
    prime:
      - usr/lib/libkmod.so*
  usbutils:
    source: https://mirrors.edge.kernel.org/pub/linux/utils/usb/usbutils/usbutils-010.tar.xz
    source-type: tar
    plugin: make
    build-attributes: [no-system-libraries]
    override-build: |
      ./configure --prefix=/usr
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/
      curl http://www.linux-usb.org/usb.ids > $SNAPCRAFT_PART_INSTALL/usr/share/usb.ids
    build-packages:
      - gcc
      - make
      - libusb-1.0-0-dev
      - libudev-dev
      - curl
    prime:
      - usr/bin/lsusb
      - usr/bin/usb-devices
      - usr/share/usb.ids
  pciutils:
    source: https://github.com/pciutils/pciutils/archive/v3.6.1.tar.gz
    source-type: tar
    plugin: make
    build-attributes: [no-system-libraries]
    override-build: |
      curl https://pci-ids.ucw.cz/v2.2/pci.ids > pci.ids
      make
      make install PREFIX=/usr DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - make
      - curl
    prime:
      - usr/sbin/lspci
      - usr/share/pci.ids
  acpica-unix:
    source: https://acpica.org/sites/acpica/files/acpica-unix-20180629.tar.gz
    source-type: tar
    plugin: make
    build-attributes: [no-patchelf]
    override-build: |
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - make
      - bison
    prime:
      - usr/bin/acpidump
      - usr/bin/iasl
      - usr/bin/acpixtract
  hdparm:
    source: https://github.com/linuxhw/build-stuff/releases/download/1.4/hdparm-9.56.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - make
    prime:
      - sbin/hdparm
  smartmontools:
    source: https://github.com/linuxhw/build-stuff/releases/download/1.4/smartmontools-6.6.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      sh autogen.sh
      ./configure --with-nvme-devicescan --prefix=/
      sed -i -e 's/ -g / /' Makefile
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - make
      - automake
    prime:
      - sbin/smartctl
  libx86emu:
    source: https://github.com/wfeldt/libx86emu/archive/2.0.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      echo '2.0' > VERSION
      rm -f git2log
      sed -i -e 's/ -g / /' Makefile
      make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - make
  hwinfo:
    after: [libx86emu]
    source: https://github.com/openSUSE/hwinfo/archive/21.56.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      echo '21.56' > VERSION
      rm -f git2log
      sed -i -e 's/ -g / /' Makefile
      CFLAGS='-I'$SNAPCRAFT_STAGE'/usr/include' LDFLAGS='-L'$SNAPCRAFT_STAGE'/usr/lib64 -lx86emu' make
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - gcc
      - make
      - flex
    prime:
      - usr/lib64/libhd*
      - usr/share/hwinfo/*
      - usr/sbin/hwinfo
  mesa-demos:
    source: ftp://ftp.freedesktop.org/pub/mesa/demos/8.3.0/mesa-demos-8.3.0.tar.bz2
    source-type: tar
    plugin: autotools
    build-attributes: [no-system-libraries]
    build-packages:
      - gcc
      - make
      - libgl1-mesa-dev
      - libglew-dev
      - freeglut3-dev
    prime:
      - bin/glxgears
      - bin/glxinfo
  perl-uri:
    source: https://cpan.metacpan.org/authors/id/E/ET/ETHER/URI-1.74.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      perl Makefile.PL
      make install DESTDIR=`pwd`/INST INSTALLSITELIB=/SITELIB
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/perl5/
      cp -fr ./INST/SITELIB/* $SNAPCRAFT_PART_INSTALL/usr/share/perl5/
    build-packages:
      - make
      - perl
  perl-http-message:
    source: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Message-6.18.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      perl Makefile.PL
      make install DESTDIR=`pwd`/INST INSTALLSITELIB=/SITELIB
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/perl5/
      cp -fr ./INST/SITELIB/* $SNAPCRAFT_PART_INSTALL/usr/share/perl5/
    build-packages:
      - make
      - perl
  perl-net-http:
    source: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/Net-HTTP-6.18.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      perl Makefile.PL
      make install DESTDIR=`pwd`/INST INSTALLSITELIB=/SITELIB
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/perl5/
      cp -fr ./INST/SITELIB/* $SNAPCRAFT_PART_INSTALL/usr/share/perl5/
    build-packages:
      - make
      - perl
  perl-try-tiny:
    source: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Try-Tiny-0.30.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      perl Makefile.PL
      make install DESTDIR=`pwd`/INST INSTALLSITELIB=/SITELIB
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/perl5/
      cp -fr ./INST/SITELIB/* $SNAPCRAFT_PART_INSTALL/usr/share/perl5/
    build-packages:
      - make
      - perl
  libwww-perl:
    source: https://cpan.metacpan.org/authors/id/E/ET/ETHER/libwww-perl-6.35.tar.gz
    source-type: tar
    plugin: make
    override-build: |
      perl Makefile.PL
      make install DESTDIR=`pwd`/INST INSTALLSITELIB=/SITELIB
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/perl5/
      cp -fr ./INST/SITELIB/* $SNAPCRAFT_PART_INSTALL/usr/share/perl5/
    build-packages:
      - make
      - perl
    prime:
      - usr/share/perl5/LWP
      - usr/share/perl5/LWP.pm
  hw-probe:
    source: https://github.com/linuxhw/build-stuff/releases/download/1.4/hw-probe-1.4-AI.tar.gz
    source-type: tar
    plugin: make
    build-attributes: [no-system-libraries]
    override-build: |
      make install DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - make
      - perl
      - curl
    stage-packages:
      - dmidecode
      - lm-sensors
    prime:
      - usr/sbin/biosdecode
      - usr/sbin/dmidecode
      - usr/bin/hw-probe
      - usr/bin/sensors
      - usr/lib/x86_64-linux-gnu/libsensors*

